language: node_js
node_js:
    - "11"
cache:
    yarn: true
    directories:
        - node_modules
install:
    - yarn
script:
    - echo "nothing!"
before_deploy:
    - yarn build
deploy:
    provider: npm
    email: onoueorigami@gmail.com
    skip_cleanup: true
    api_key:
        secure: PUp4Pj5YexkLrPdEXL5tdZgovQKEUGT5Q1p3tSl4izPUPElKurxhTgK+yPx7DBfL85a0l00zVcZ1IlkqauOlK2lg2b8F320wYy2TfO30zrsRuOszjMciyF/s1IaZ2weYxQQhu4pfqwRgKl7/sjwwCgBwnsTIBBGykR1qL5HPXPIyELczb6nHe8Q0ex1PO3TfpIXHywVA/7xO/39/olh/Pst7P27b504qfV9kpJYbbraNiiGRXmgDM0g3lYIIcB8J1YFc3o1NkUBwNe0XhGGDhzy4C+jm0u9zEXs1vLpz78zdysazTRhPEwjUeZZ+aSh7NHNV6VhJuEbF9GzRptBrO6BU9VEcl19tjTD2efW9c/n+QtRwF82wJxiV47cXqcNVKoEvSJ/ybdRKgJ3cIiCS4Q/MI181L61CShOTzKOsZ6mPTgXlp366yhKBakC0kREDJvzcXKBDIoswiEGvujUlpjwr2tjNiLo28y8Nlj9cdEzFFo932Vpyn4EWHDUehU0+qlnaNiwVA5bQRmoWApPE4duc2qlAWlZDjRQ9KyUeGvQ8SPxGypLUheWebmRMQeS4pfkS+XjNfNME/1EpcWqCrpEdZFiAvcTVecod2v7m/ZE3KhckcLasA1jDura4LR2fnTaiaW5tHJddHCKVCM8X1Wf75xk/fUnArhZRRLSQ7uw=
    on:
        tags: true
